project:
  type: website

website:
  title: "Ashley Lee"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Marketing Projects"
        href: marketing-projects.qmd
      - text: "Strategic Marketing"
        href: strategic-marketing.qmd
      - text: "Resume"
        href: resume.qmd
  google-analytics: "G-CR0G416PNV"


format:
  html:
    theme: [sandstone, theme.scss]
    toc: true
    include-in-header: includes/gtm-head.html      # Injects GTM script into <head>
    include-before-body: includes/gtm-body.html    # Injects GTM noscript immediately after <body> opens

